"""empty message

Revision ID: e881221664db
Revises: 0afcc2fbde16
Create Date: 2020-04-30 19:52:47.797053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e881221664db'
down_revision = '0afcc2fbde16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               nullable=False)
    op.add_column('user_task', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_task', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_task', type_='foreignkey')
    op.drop_column('user_task', 'user_id')
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120),
               nullable=True)
    # ### end Alembic commands ###
